#!/bin/bash

RED="\e[31m"
YELLOW=$'\e[33m'
RESET="\e[0m"

if [[ "$#" -ne 2 ]]; then
    echo -e "${RED}[x]${RESET} Error: Incorrect number of arguments"

    echo -e "\nUsage:"
    echo -e "\tlisten linux <port>"
    echo -e "\tlisten windows <port>"
    exit 1
fi

if ! command -v rcat >/dev/null 2>&1; then
    echo -e "${RED}[x]${RESET} rcat not installed"
    exit 1
fi

if [[ "$XDG_SESSION_TYPE" == "x11" ]] && ! command -v xclip >/dev/null 2>&1; then
    echo -e "${RED}[x]${RESET} xclip not installed"
    exit 1
fi

copy=""
if uname -r | grep -q "microsoft"; then
    copy='/mnt/c/Windows/System32/clip.exe'
elif [[ "$XDG_SESSION_TYPE" == "x11" ]]; then
    copy='xclip -selection clipboard'
else
    copy='wl-copy'
fi

if [[ "$1" == "linux" ]]; then
    read -r rows cols < <(stty size)
    fix_command="export TERM=xterm-256color; stty rows $rows cols $cols; alias ls='ls --color=auto'; alias grep='grep --color=auto'; alias ip='ip --color=auto'"
    echo -n "$fix_command" | $copy
    echo -e "\n${YELLOW}[!]${RESET} Fix command copied to clipboard"
    echo -e "\n${YELLOW}[!]${RESET} Fix command: $fix_command"

    stty raw -echo
    rcat listen -ie "/usr/bin/env python3 -c 'import pty; pty.spawn(\"/bin/bash\")'" "$2"
    reset
elif [[ "$1" == "windows" ]]; then
    echo -ne "\n"
    rlwrap ncat -lvnp "$2"
else
    echo -e "\n${RED}[x]${RESET} Invalid option\n"
    exit 1
fi
