#!/bin/bash

RED="\e[31m"
BLUE="\e[34m"
YELLOW="\e[33m"
ENDCOLOR="\e[0m"

if [[ "$#" -ne 2 ]]; then
    echo -e "${RED}[x]${ENDCOLOR} Error: Incorrect number of arguments"

    echo -e "\nUsage:"
    echo -e "\tlisten linux <port>"
    echo -e "\tlisten windows <port>"
    exit 1
fi

if ! command -v rcat >/dev/null 2>&1; then
    echo -e "${RED}[x] rcat not installed"
    exit 1
fi

if uname -r | grep -q "microsoft"; then
    copy='/mnt/c/Windows/System32/clip.exe'
elif [[ "$XDG_SESSION_TYPE" == "x11" ]]; then
    copy='xclip -selection clipboard'
else
    copy='wl-copy'
fi

if [[ "$1" == "linux" ]]; then
    read -r rows cols < <(stty size)
    echo -n "stty rows $rows cols $cols" | $copy
    echo -e "\n${BLUE}[!]${ENDCOLOR} Fix stty size on the reverse shell"
    echo -e "${BLUE}[!]${ENDCOLOR} ${YELLOW}stty rows $rows cols $cols${ENDCOLOR} copied to clipboard\n"

    stty raw -echo
    rcat listen -ie "$(command -v script) -qc $(command -v bash) /dev/null; export TERM=xterm-256color; alias ls='ls --color=auto'; alias grep='grep --color=auto'; alias ip='ip --color=auto'" "$2"
    reset
elif [[ "$1" == "windows" ]]; then
    echo -ne "\n"
    rlwrap ncat -lvnp "$2"
else
    echo -e "\n${RED}[x]${ENDCOLOR} Invalid option\n"
    exit 1
fi
