#!/bin/bash

RED="\e[31m"
ENDCOLOR="\e[0m"

outfile_tcp="tcp_scan.txt"
outfile_udp="udp_scan.txt"
udp=0
help=0
current_filename=""
positional_amount=0
target=""

trap ctrl_c INT

function ctrl_c() {
    sudo rm -f "$current_filename"
    echo -e "\n${RED}[x]${ENDCOLOR} Aborting scan" >&2
    exit 1
}

function usage() {
    echo "Usage: scan [options] <ip>"
    echo -e "\nOptions:"
    echo -e "\t-u\tUDP scan"
    echo -e "\t-o FILE\tOutput file name"
    echo -e "\t-h \tPrint this message and exit"
}

while [ "$#" -gt 0 ]; do
    case "$1" in
    -u)
        udp=1
        current_filename="$outfile_udp"
        shift 1
        ;;
    -o)
        current_filename="$2"
        shift 2
        ;;
    -h)
        help=1
        shift 1
        ;;

    -*)
        echo -e "${RED}[x]${ENDCOLOR} Error: Invalid option: $1\n" >&2
        usage
        exit 1
        ;;
    *)
        positional_amount=$((positional_amount + 1))
        if [[ "$positional_amount" -gt 1 ]]; then
            echo -e "${RED}[X]${ENDCOLOR} Error: Can't have more than 1 positional argument\n" >&2
            usage
            exit 1
        fi
        target="$1"
        shift 1
        ;;
    esac
done

if [[ "$help" -eq 1 ]]; then
    usage
    exit 0
fi

if [[ -z "$current_filename" ]]; then
    if [[ "$udp" -eq 1 ]]; then
        current_filename="$outfile_udp"
    else
        current_filename="$outfile_tcp"
    fi
fi

if [[ -z "$target" ]]; then
    echo -e "${RED}[x]${ENDCOLOR} Error: Missing IP or hostname\n" >&2
    usage
    exit 1
fi

if [[ "$udp" -eq 1 ]]; then
    if [[ -f /etc/arch-release ]]; then
        sudo nmap -sU -F -sCV -T4 --open -vvv -n "$target" -oN "$current_filename" | bat -pp -l python
        sudo chown "$USER":"$USER" "$current_filename"
    else
        sudo nmap -sU -F -sCV -T4 --open -vvv -n "$target" -oN "$current_filename" | batcat -pp -l python
        sudo chown "$USER":"$USER" "$current_filename"
    fi
else
    if [[ -f /etc/arch-release ]]; then
        sudo nmap -sS -p- -sCV -T4 --open -vvv -n "$target" -oN "$current_filename" | bat -pp -l python
        sudo chown "$USER":"$USER" "$current_filename"
    else
        sudo nmap -sS -p- -sCV -T4 --open -vvv -n "$target" -oN "$current_filename" | batcat -pp -l python
        sudo chown "$USER":"$USER" "$current_filename"
    fi
fi
